title: 100% Route (1.9)
version: v2

route:
  use: ./main.yaml

config:
- use: sobolews/celer-presets/botw/full.yaml
- use: ./locations.yaml
- use: ./100.yaml
- plugins:
  - use: link
  - use: split-format
    with:
      Shrines: ".var(counter-korok) - .prop(text)"
  - use: variables
    with:
      init:
        with-dlc: 0
        great-plateau-count: 1
        map-pct-items-total: 1209
      split-types:
        - Shrines
        - Towers
        - UserDefined
      expose: true

- tags:
    user-defined-split:
      color: black
      background: orange
      split-type: UserDefined
    gale:
      color: black
      background: lime
    fury:
      color: black
      background: orange
    val:
      color:
        dark: "#ff7272"
        light: "#800000"
      bold: true

      # TODO: delete this after Piston fixes Warp vars issue
    counter-memory:
      split-type: null
    counter-warp:
      color: black
      background: cyan
      split-type: null

- presets:
    _Snap:
      Quest:
        text: $(0)
        icon: camera
        icon-priority: 2
        comment: SNAP for quest
  # TODO: reenable this after Piston fixes Warp vars issue
    # _Memory:
    #   _Parts:
    #     DefaultSplitConfig:
    #       presets: _Memory::Parts::NoSplitByDefault
    # _Warp:
    #   _Parts:
    #     DefaultSplitConfig:
    #       presets: _Warp::Parts::NoSplitByDefault


- splits:
  - user-defined-split
